### ISSUE TITLE
Do we need an anonymous mode?

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/diracx-web#1]
In the previous webapp it was possible for people to view some information without being logged in. I think this was mostly used for letting people access monitoring data. Given this data will be exposed elsewhere (grafana) I think we can probably drop support for anonymous access.

If we do need anonymous access, changes will be needed in DiracX as well to make API routes public as we currently assume people always have a token, though we should have use cases first.

**Comment by fstagni** [comment]
I concur.

**Comment by aldbr** [comment]
Described as a discussion here: https://github.com/DIRACGrid/diracx-web/discussions/17
