### ISSUE TITLE
Landing page design

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/diracx-web#2]
Opening this issue to collect ideas I have as I started thinking about it. The landing page should have an option for selecting which VO to login as. This can be dynamically computed from the `vo:*` scopes in `.well-known/oidc-configuration`.

Advanced users might also want the option to set the group, specific properties and perhaps even the API hostname (so people can develop on localhost against a real installation). These options should all be hidden to some extent.

**Comment by aldbr** [comment]
Created two discussions based on this issue:
- https://github.com/DIRACGrid/diracx-web/discussions/14
- https://github.com/DIRACGrid/diracx-web/discussions/13
