### ISSUE TITLE
Implement a simple `Profile` component

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/diracx-web#26]
When a user connects to the web application, he/she might want to get knowledge about:
- username (`preferred_username`)
- VO (`vo`)
- group (`dirac_group`)
- properties (`dirac_properties`)

The idea is to implement https://github.com/DIRACGrid/diracx-web/discussions/25

## Plan of work

- Create a `Design ideas` discussion and a mockup interface to discuss about how it should look
- Implement a components that would extract data from the access token and display them according to the chosen design
- Integrate the new component into a page
- Test it with `jest`

**Comment by vanmsantos** [comment]
This is my designer idea.
![interface](https://github.com/DIRACGrid/diracx-web/assets/102741959/6cdadc33-63da-475c-9560-be440d5f1bef)

**Comment by esilvaju** [comment]
Nice @vanmsantos ! That would be a nice `ProfilePageEdit`. 

Could you build a `ProfilePage ` to show the `UserProfileData ` with what could could be a EditButton that opens the `ProfilePageEdit` ?

**Comment by aldbr** [comment]
Great, thanks for your contribution @vanmsantos !
Out of curiosity, what did you use to create your design idea?

But currently, we have no way of editing the profile, we just get the user information from an access token and we want to display it.

Important details:
- A user may have different accounts (e.g. a user that would be part of different VOs would have different accounts). 
- A user can switch between different groups, which means different properties.

To avoid being lost (am I connected as VO_a user or VO_b user? Am I a simple user or do I have admin rights in this session?), the user wants to get an easy access to these details.

I was thinking of displaying the information from the `ProfileButton.tsx` first, such as:
- The user opens the menu at the top-right corner
- The user immediately sees the essential details 

![image](https://github.com/DIRACGrid/diracx-web/assets/19813740/95486db6-e2a9-494a-813f-ea51eca747e8)

Any opinion?

**Comment by vanmsantos** [comment]
Hello @aldbr and @esilvaju 
To create this interface design, I used the **Pencil** tool. I already work with it in my day-to-day, however, the tool only creates static screens, without the feature of componentization. 
I am studying a tool that creates dynamic prototypes that can assist the developer in coding the screen.

**Comment by esilvaju** [comment]
Create @vanmsantos ! Looking forward.

**Comment by vanmsantos** [comment]
Hello @aldbr and @esilvaju ,
I would like to share with you the interface designs I developed.
This interface design I used the Figma tool. And I developed 3 different access accounts to the profile.

Profile page - Owner's View Create
Profile page - Owner's View Edit
Profile page - Visitor's View

What do you think?

![Profile page - Owner's View Create](https://github.com/DIRACGrid/diracx-web/assets/102741959/c0c0caf7-aa63-43a6-8e2d-222421c49ed4)
![Profile page - Owner's View Edit](https://github.com/DIRACGrid/diracx-web/assets/102741959/679cb769-52f2-497d-97d6-7764bcf12794)
![Profile page - Visitor's View](https://github.com/DIRACGrid/diracx-web/assets/102741959/81e0930c-eed5-4c17-9974-85dad49fedc3)

**Comment by aldbr** [comment]
Thank you @vanmsantos for your dedication and the great work on the mockup interfaces!

However, I would like to steer us back towards the specific needs of the dirac users. Our main objective is quite straightforward - we aim to display just the user's name and their group:

- Users do not require the functionality to view other users' profiles.
- Our data needs are minimal; we only need to utilize a few pieces of information (name, vo, group, properties) that we receive from the back end.

Let’s focus on creating a simple yet effective [interface](https://github.com/DIRACGrid/diracx-web/issues/26#issuecomment-2022934636) that aligns with these goals. 
Also, I must admit that the title of the issue might have been misleading. My apologies for any confusion this may have caused.

Your enthusiasm and creativity are truly valuable though. 
Thank you again for your hard work and adaptability!

**Comment by vanmsantos** [comment]
No problem, @aldbr , the most important thing is that we've made a start on the interface. Now we just need to adjust it to fit our project's needs ;) 

I'll make the necessary adjustments and send it to you shortly.

**Comment by vanmsantos** [comment]
Hey @aldbr 

I made some adjustments to the interface.

However, I have some questions:
1-What are the pieces of information that will be loaded into the interface? (through the backend)

2-Will this connection between users be established based on which hierarchy? By peers (coordinator -> team) ?
Or by VO (I'm a regular user connected to VO_a, and I can see all my peers connected to the same VO_a. Consequently, I can navigate through my peers who belong to the same VO_a, even though I'm just a regular user).

In option 2, if it holds true, I think we could establish a rule: only users with an admin profile would be able to navigate among their peers as long as they belong to the same VO.

![Profile page - Owner's View Create Simple](https://github.com/DIRACGrid/diracx-web/assets/102741959/124c1446-0fef-42a8-b167-ceec7a5f2a6f)

**Comment by esilvaju** [comment]
Good stuff guys ! :)

What you guys say about schedule a zoom call to fine-tune the understandings about the needs of the screen ? 👍
